//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudDeliveryMobile.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrdersApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudDeliveryMobile.Resources.OrdersApiResources", typeof(OrdersApiResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/CheckDistanceTime.
        /// </summary>
        internal static string ApproximateTrace {
            get {
                return ResourceManager.GetString("ApproximateTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/delivered.
        /// </summary>
        internal static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/gettrace.
        /// </summary>
        internal static string GetTrace {
            get {
                return ResourceManager.GetString("GetTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/PendingList.
        /// </summary>
        internal static string PendingOrders {
            get {
                return ResourceManager.GetString("PendingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/pickup.
        /// </summary>
        internal static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://clouddelivery.azurewebsites.net/api/orders/settrace.
        /// </summary>
        internal static string SetTrace {
            get {
                return ResourceManager.GetString("SetTrace", resourceCulture);
            }
        }
    }
}
